### ISSUE TITLE
box not found ... possible fix?

### ISSUE THREAD

**Issue by apanzerj** [litaio/development-environment#3]
I had the issue with box not found and was able to fix it by adding:

````
      config.vm.box_url = "https://atlas.hashicorp.com/litaio/boxes/development-environment/versions/1.0.0/providers/virtualbox.box"
````

**Comment by jimmycuadra** [comment]
Sorry for the trouble! I just merged a brand new development environment using Docker to master. This replaces the Vagrant-box-based development environment. Give that a shot instead!
